const Constants={

    Authentication:{
        Getstarted:"Get started with SwiftBel",
        continue:'Continue',
        Login:'Login',
        haveanaccount:'Already have an account?',
        Signupwith:'Sign up with',
        BytappingCreateanAccount:'By tapping Create an Account or Log In, I agree to SwiftBel’s ',
        TermsofService:'Terms of Service, ',
        PaymentsTermsofService:'Payments Terms of Service ',
        And:'and ',
        NondiscriminationPolicy:'Nondiscrimination Policy ',
        acknowledge:'and acknowledge the ',
        PrivacyPolicy:'Privacy Policy.',
        emailforregistration:'Email Sign up:',
        Next:'Next',
        Verifyyouremail:'Verify Your Email',
        EmailSent:'We sent an email to ',
        EmailtoComplete:' If you haven`t recived the verification email, ',
        SpamFolder:'Please check your spam folder.',
        cantfindtheemail:'',
        needHelp:'Need help? ',
        ContactUs:'Contact Us',
        ResendEmail:'Resend Email',
        SetUpPassword:'Create Your Password',
        TypePassword:'Password',
        passwordConfirmation:'Confirm Password',
        Passwordweak:'Password strength: Weak',
        Cantcontainemailaddress:`Can't contain your name or email address`,
        Atleastcharacters:'Atleast 8 characters with one upper case',
        Containssymbol:'Contains a number and symbol',
        Passwordgood:'Password strength: Good',
        Passwordnotmatching:'Password is not matching',
        Welcometo:'Welcome to',
        signUp:'Signup',
        Donthaveanaccount:'Don’t have an account?',
        LogInwith:'Log In with',
        LoginwithMail:"Log in with Mail:",
        password:'Password',
        Createacompanysteps:'Create a user profile in 3 steps',
        Letsdoit:'Let’s do it'
    },
    profile:{
        TellUsaname:'Tell Us your full name',
        Businessname:'Business name *',
        BusinessNumber:'Business Number * ',
        back:'Back',
        firstName:'First Name',
        lastName:'Last Name',
        AddMoreOwner:'+ Add More Owners',
        BirthProvinceState:'Province of birth',
        BirthCountry:'Country of birth',
        BirthCity:'City of birth',
        Country:'Country of residence',
        Address:'Address',
        ProvinceState :'Province',
        City:'City',
        PhotooftheID:'Photo of the ID'
    },
    TYPE:{
        registerMail:'REGISTER_MAIL' ,
        registerId:'REGISTER_ID',
        LoginMail:'LOGIN_MAIL',
        createProfile:'CREATE_PROFILE',
        mobileNumber:'MOBILE_NUMBER',
        addService:'ADD_SERVICE',
        addPicture:'ADD_PICTURE',
        addOwner:'ADD_OWNER',
        Businessname:'BUSINESS_NAME',
        addlocation:'ADD_LOCATION',
        authToken:'AUTH_TOKEN',
        address:'ADDRESS',
        profileToken:'PROFILE_TOKEN',
        PostData:'POST_DATA',
        profileDetails:'PROFILE_DETAILS',
        bannerDetails:'BANNER_DETAILS',
        licenseType:'LICENSE_TYPE'
    }
    
}
export default Constants